package com.qwerty.morningstarfitness.navigation

const val ROUTE_SPLASH = "splash"
const val ROUTE_ONBOARDING = "onboarding"
const val ROUTE_ENTRY = "entry"
const val ROUTE_LOGIN = "login"
const val ROUTE_SCAN_ENTRY = "scan_entry"
const val ROUTE_REGISTRATION = "registration"
const val ROUTE_PLAN = "plan"
const val ROUTE_PAYMENT = "payment"
const val ROUTE_RENEW = "renew"
const val ROUTE_RENEW_PAYMENT = "renew_payment"
const val ROUTE_SUCCESS = "success"
const val ROUTE_HOME = "home"
const val ROUTE_ATTENDANCE = "attendance"
const val ROUTE_SHOP = "shop"
const val ROUTE_ORDER_SUCCESS = "order_success"
const val ROUTE_PROFILE = "profile"
const val ROUTE_QR_ENTRY = "qr_entry"
const val ROUTE_PASSWORD_ENTRY = "password_entry"
